[package]
name = "modbus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Modbus TCP slave for simbus"

[lints]
workspace = true

[dependencies]
engine = { workspace = true }
spec = { workspace = true }
tokio = { workspace = true }
tokio-modbus = { workspace = true, features = ["tcp-server"] }
tracing = { workspace = true }
