[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Protocol-agnostic device simulation engine"

[lints]
workspace = true

[dependencies]
parking_lot = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
spec = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
